# Generated by Django 4.0.5 on 2022-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Long-Short term', 'Long-Short term')], default='Long-Short term', max_length=20),
        ),
    ]
